# Rules and licenses Provenant intentionally excludes when building the license index.
#
# Rule identifiers must match LoadedRule.identifier values (typically full filenames).
# License entries must match LoadedLicense.key values.
#
# This manifest keeps the small, reviewable curation decisions:
# - `ignored_rules` / `ignored_licenses` remove upstream entries.
# - file-based add/replace overlays live under `resources/license_detection/overlay/`
#   using the exact upstream `.RULE` / `.LICENSE` syntax.
# - overlay semantics are collision-based: matching identifiers/keys replace
#   upstream entries, new identifiers/keys are added.
#
# The active curation fingerprint and applied changes are embedded into the
# generated license artifact and surfaced in scan output headers.
#
# Current policy notes:
# - `gpl-2.0_and-unknown-license-reference_1.RULE` is excluded in response to
#   upstream ScanCode PR 4683, where the matched Android-generated header text
#   is described as containing no copyrightable information.
# - `unknown_10.RULE` is replaced via a local overlay file with the narrower
#   upstream-reviewed shape from PR 4671: keep the unknown reference rule, but
#   require a referenced filename of `LICENSE` so plain text mentions stop
#   overmatching.
# - Other surveyed cases such as PR 4666, PR 4674, and PR 4694 are already
#   present in the pinned ScanCode dataset, so they do not need downstream
#   overlays here.

ignored_rules = [
  "gpl-2.0_and-unknown-license-reference_1.RULE",
]

ignored_licenses = []
