# @oss-disable[end= ]: load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
# @oss-disable[end= ]: load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_library(
    name = "library",
    srcs = ["src/lib.rs"],
)

# @oss-disable: rust_unittest(
    rust_test( # @oss-enable
    name = "test",
    srcs = ["tests/test.rs"],
)
