#[cfg(test)]
mod tests {
    use crate::parsers::{PackageParser, PoetryLockParser};

    #[test]
    fn test_poetry_lock_top_level_package_entries_keep_optional_raw_but_do_not_infer_runtime() {
        use std::fs;
        use tempfile::TempDir;

        let content = r#"# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:test"},
]

[[package]]
name = "pytest"
version = "7.4.0"
description = "pytest: simple powerful testing with Python"
optional = true
python-versions = ">=3.7"
files = [
    {file = "pytest-7.4.0-py3-none-any.whl", hash = "sha256:test"},
]

[metadata]
lock-version = "2.0"
python-versions = "^3.8"
content-hash = "test"
"#;

        let temp_dir = TempDir::new().expect("Failed to create temp dir");
        let lock_path = temp_dir.path().join("poetry.lock");
        fs::write(&lock_path, content).expect("Failed to write poetry.lock");

        let package_data = PoetryLockParser::extract_first_package(&lock_path);

        assert_eq!(package_data.dependencies.len(), 2);

        let requests = package_data
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("requests"))
            .expect("Should find requests dependency");

        assert_eq!(requests.is_optional, None);
        assert_eq!(requests.is_runtime, None);
        assert_eq!(
            requests
                .extra_data
                .as_ref()
                .and_then(|data| data.get("poetry_optional"))
                .and_then(|value| value.as_bool()),
            Some(false)
        );

        let pytest = package_data
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("pytest"))
            .expect("Should find pytest dependency");

        assert_eq!(pytest.is_optional, None);
        assert_eq!(pytest.is_runtime, None);
        assert_eq!(
            pytest
                .extra_data
                .as_ref()
                .and_then(|data| data.get("poetry_optional"))
                .and_then(|value| value.as_bool()),
            Some(true)
        );
    }

    #[test]
    fn test_poetry_lock_extras_are_optional_without_forcing_runtime_classification() {
        use std::fs;
        use tempfile::TempDir;

        let content = r#"# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "attrs"
version = "21.4.0"
optional = false
python-versions = ">=3.8"
files = [
    {file = "attrs-21.4.0-py3-none-any.whl", hash = "sha256:test"},
]

[package.extras]
tests = ["pytest (>=7.0.0)"]

[metadata]
lock-version = "2.0"
python-versions = "^3.8"
"#;

        let temp_dir = TempDir::new().expect("Failed to create temp dir");
        let lock_path = temp_dir.path().join("poetry.lock");
        fs::write(&lock_path, content).expect("Failed to write poetry.lock");

        let package_data = PoetryLockParser::extract_first_package(&lock_path);
        let attrs = package_data
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("attrs@21.4.0"))
            .expect("Should find attrs dependency");

        let pytest = attrs
            .resolved_package
            .as_ref()
            .expect("resolved package should exist")
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("pytest"))
            .expect("Should find pytest extra dependency");

        assert_eq!(pytest.scope, Some("tests".to_string()));
        assert_eq!(pytest.is_optional, Some(true));
        assert_eq!(pytest.is_runtime, None);
    }

    #[test]
    fn test_poetry_lock_dependency_table_preserves_optional_flag() {
        use std::fs;
        use tempfile::TempDir;

        let content = r#"# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "consumer"
version = "1.0.0"
optional = false
python-versions = ">=3.8"
files = [
    {file = "consumer-1.0.0-py3-none-any.whl", hash = "sha256:test"},
]

[package.dependencies]
rich = { version = ">=13", optional = true }

[metadata]
lock-version = "2.0"
python-versions = "^3.8"
"#;

        let temp_dir = TempDir::new().expect("Failed to create temp dir");
        let lock_path = temp_dir.path().join("poetry.lock");
        fs::write(&lock_path, content).expect("Failed to write poetry.lock");

        let package_data = PoetryLockParser::extract_first_package(&lock_path);
        let consumer = package_data
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("consumer@1.0.0"))
            .expect("Should find consumer dependency");

        let rich = consumer
            .resolved_package
            .as_ref()
            .expect("resolved package should exist")
            .dependencies
            .iter()
            .find(|d| d.purl.as_ref().unwrap().contains("rich"))
            .expect("Should find rich dependency");

        assert_eq!(rich.scope, Some("dependencies".to_string()));
        assert_eq!(rich.is_runtime, Some(true));
        assert_eq!(rich.is_optional, Some(true));
    }
}
